In [27]:
#printing the file
import pandas as pd
df=pd.read_csv("/content/Dataset of Diabetes .csv")
df2=pd.read_csv("/content/adult.csv")
print('information of the dataset')
df2.head()

information of the dataset

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
#printing the information of the dataset1 that is diabetes
import pandas as pd
df=pd.read_csv("/content/Dataset of Diabetes .csv")
print('information of the dataset')
df.info()

information of the dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

In [ ]:
import pandas as pd
df=pd.read_csv("/content/Dataset of Diabetes .csv")
df.isnull()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [28]:
#handling categorical values in the diabets dataset
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)

# Perform One-Hot Encoding
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_data = encoder.fit_transform(df[categorical_cols])

# Create a new DataFrame with encoded columns
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate encoded and original DataFrames
df = pd.concat([df, encoded_df], axis=1)

# Drop original categorical columns
df.drop(categorical_cols, axis=1, inplace=True)

# Display the updated DataFrame
df.head()

Categorical columns: Index(['Gender', 'CLASS'], dtype='object')

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_F,Gender_M,Gender_f,CLASS_N,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,735,34221,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,420,47975,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,680,87656,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,504,34223,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [39]:
#handling categorical datavalues in the adult dataset
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)

# Perform One-Hot Encoding
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_data = encoder.fit_transform(df2[categorical_cols])

# Create a new DataFrame with encoded columns
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate encoded and original DataFrames
df2 = pd.concat([df2, encoded_df], axis=1)

# Drop original categorical columns
df2.drop(categorical_cols, axis=1, inplace=True)

# Display the updated DataFrame
df2.head()

Categorical columns: Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'gender', 'native-country', 'income'],
      dtype='object')

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_?,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_<=50K,income_>50K
0,25,226802,7,0,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,38,89814,9,0,0,50,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,28,336951,12,0,0,40,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,44,160323,10,7688,0,40,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,18,103497,10,0,0,30,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [47]:
#handling outliers values in dataset diabetes

import pandas as pd

# Load the dataset
df = pd.read_csv("/content/Dataset of Diabetes .csv")

# Calculate quantiles and IQR for 'AGE' column
Q1 = df['AGE'].quantile(0.25)
Q3 = df['AGE'].quantile(0.75)
IQR = Q3 - Q1

# Define upper and lower bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter data to remove outliers
df_no_outliers = df[(df['AGE'] >= lower_bound) & (df['AGE'] <= upper_bound)]
df_no_outliers.head()
# Now, df_no_outliers contains the dataset without outliers in the 'AGE' column.

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
5,634,34224,F,45,2.3,24,4.0,2.9,1.0,1.0,1.5,0.4,21.0,N
6,721,34225,F,50,2.0,50,4.0,3.6,1.3,0.9,2.1,0.6,24.0,N

In [49]:
#handling outliers in adult dataset
import pandas as pd

# Load the dataset
df = pd.read_csv("/content/adult.csv")

# Calculate quantiles and IQR for 'AGE' column
Q1 = df['hours-per-week'].quantile(0.25)
Q3 = df['hours-per-week'].quantile(0.75)
IQR = Q3 - Q1

# Define upper and lower bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter data to remove outliers
df_no_outliers = df[(df['hours-per-week'] >= lower_bound) & (df['hours-per-week'] <= upper_bound)]
df_no_outliers.head()
# Now, df_no_outliers contains the dataset without outliers in the 'AGE' column.

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K

In [57]:
import pandas as pd
df=pd.read_csv("/content/Dataset of Diabetes .csv")
from sklearn.preprocessing import MinMaxScaler, StandardScaler
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()
numerical_features = ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']
df[numerical_features] = minmax_scaler.fit_transform(df[numerical_features])
df[numerical_features] = standard_scaler.fit_transform(df[numerical_features])
print(df[numerical_features])

          AGE      Urea        Cr     HbA1c      Chol        TG       HDL  \
0   -0.401144 -0.144781 -0.382672 -1.334983 -0.509436 -1.035084  1.810756
1   -3.130017 -0.212954 -0.115804 -1.334983 -0.893730 -0.678063 -0.158692
2   -0.401144 -0.144781 -0.382672 -1.334983 -0.509436 -1.035084  1.810756
3   -0.401144 -0.144781 -0.382672 -1.334983 -0.509436 -1.035084  1.810756
4   -2.334096  0.673299 -0.382672 -1.334983  0.028576 -0.963680 -0.613180
..        ...       ...       ...       ...       ...       ...       ...
995  1.986619  2.002680  0.467970 -0.505840  2.026906 -0.463850 -0.007196
996 -2.561502 -0.724254 -0.149162  1.586758 -0.586295 -0.106828 -0.764676
997 -2.675205  0.673299  0.201102 -0.624289 -0.586295 -0.892276 -0.007196
998 -1.765581  0.230173 -0.165842 -0.624289  0.336011 -0.249637  0.598788
999  0.053668 -0.042521 -0.032408 -0.545323 -0.816871 -0.463850 -0.158692

          LDL      VLDL       BMI
0   -1.085457 -0.369958 -1.124622
1   -0.457398 -0.342649 -1.326239
2   -1.085457 -0.369958 -1.124622
3   -1.085457 -0.369958 -1.124622
4   -0.547121 -0.397267 -1.729472
..        ...       ...       ...
995 -0.726566 -0.342649  0.085078
996 -0.188229  3.699116  1.536719
997 -0.188229  1.705543 -0.439125
998  0.260385  3.316787  2.202054
999  0.350107 -0.315340  0.689928

[1000 rows x 10 columns]

In [62]:
import pandas as pd
df2=pd.read_csv("/content/adult.csv")
from sklearn.preprocessing import MinMaxScaler, StandardScaler
minmax_scaler = MinMaxScaler()
numerical_features = ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
df2[numerical_features] = minmax_scaler.fit_transform(df2[numerical_features])
print(df2)

            age     workclass    fnlwgt     education  educational-num  \
0      0.109589       Private  0.145129          11th         0.400000
1      0.287671       Private  0.052451       HS-grad         0.533333
2      0.150685     Local-gov  0.219649    Assoc-acdm         0.733333
3      0.369863       Private  0.100153  Some-college         0.600000
4      0.013699             ?  0.061708  Some-college         0.600000
...         ...           ...       ...           ...              ...
48837  0.136986       Private  0.165763    Assoc-acdm         0.733333
48838  0.315068       Private  0.096129       HS-grad         0.533333
48839  0.561644       Private  0.094462       HS-grad         0.533333
48840  0.068493       Private  0.128004       HS-grad         0.533333
48841  0.479452  Self-emp-inc  0.186482       HS-grad         0.533333

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male
1      Married-civ-spouse    Farming-fishing      Husband  White    Male
2      Married-civ-spouse    Protective-serv      Husband  White    Male
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male
4           Never-married                  ?    Own-child  White  Female
...                   ...                ...          ...    ...     ...
48837  Married-civ-spouse       Tech-support         Wife  White  Female
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male
48839             Widowed       Adm-clerical    Unmarried  White  Female
48840       Never-married       Adm-clerical    Own-child  White    Male
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female

       capital-gain  capital-loss  hours-per-week native-country income
0          0.000000           0.0        0.397959  United-States  <=50K
1          0.000000           0.0        0.500000  United-States  <=50K
2          0.000000           0.0        0.397959  United-States   >50K
3          0.076881           0.0        0.397959  United-States   >50K
4          0.000000           0.0        0.295918  United-States  <=50K
...             ...           ...             ...            ...    ...
48837      0.000000           0.0        0.377551  United-States  <=50K
48838      0.000000           0.0        0.397959  United-States   >50K
48839      0.000000           0.0        0.397959  United-States  <=50K
48840      0.000000           0.0        0.193878  United-States  <=50K
48841      0.150242           0.0        0.397959  United-States   >50K

[48842 rows x 15 columns]

In [63]:
import pandas as pd
df2=pd.read_csv("/content/adult.csv")
from sklearn.preprocessing import MinMaxScaler, StandardScaler
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()
numerical_features = ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
df2[numerical_features] = minmax_scaler.fit_transform(df2[numerical_features])
df2[numerical_features] = standard_scaler.fit_transform(df2[numerical_features])
print(df2)

            age     workclass    fnlwgt     education  educational-num  \
0     -0.995129       Private  0.351675          11th        -1.197259
1     -0.046942       Private -0.945524       HS-grad        -0.419335
2     -0.776316     Local-gov  1.394723    Assoc-acdm         0.747550
3      0.390683       Private -0.277844  Some-college        -0.030373
4     -1.505691             ? -0.815954  Some-college        -0.030373
...         ...           ...       ...           ...              ...
48837 -0.849254       Private  0.640492    Assoc-acdm         0.747550
48838  0.098933       Private -0.334178       HS-grad        -0.419335
48839  1.411808       Private -0.357510       HS-grad        -0.419335
48840 -1.213941       Private  0.111984       HS-grad        -0.419335
48841  0.974183  Self-emp-inc  0.930494       HS-grad        -0.419335

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male
1      Married-civ-spouse    Farming-fishing      Husband  White    Male
2      Married-civ-spouse    Protective-serv      Husband  White    Male
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male
4           Never-married                  ?    Own-child  White  Female
...                   ...                ...          ...    ...     ...
48837  Married-civ-spouse       Tech-support         Wife  White  Female
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male
48839             Widowed       Adm-clerical    Unmarried  White  Female
48840       Never-married       Adm-clerical    Own-child  White    Male
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female

       capital-gain  capital-loss  hours-per-week native-country income
0         -0.144804     -0.217127       -0.034087  United-States  <=50K
1         -0.144804     -0.217127        0.772930  United-States  <=50K
2         -0.144804     -0.217127       -0.034087  United-States   >50K
3          0.886874     -0.217127       -0.034087  United-States   >50K
4         -0.144804     -0.217127       -0.841104  United-States  <=50K
...             ...           ...             ...            ...    ...
48837     -0.144804     -0.217127       -0.195490  United-States  <=50K
48838     -0.144804     -0.217127       -0.034087  United-States   >50K
48839     -0.144804     -0.217127       -0.034087  United-States  <=50K
48840     -0.144804     -0.217127       -1.648120  United-States  <=50K
48841      1.871315     -0.217127       -0.034087  United-States   >50K

[48842 rows x 15 columns]

In [64]:
import pandas as pd
df=pd.read_csv("/content/Dataset of Diabetes .csv")
from sklearn.preprocessing import MinMaxScaler, StandardScaler
minmax_scaler = MinMaxScaler()
numerical_features = ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']
df[numerical_features] = minmax_scaler.fit_transform(df[numerical_features])
print(df[numerical_features])

          AGE      Urea        Cr     HbA1c      Chol        TG       HDL  \
0    0.508475  0.109375  0.050378  0.264901  0.407767  0.044444  0.226804
1    0.101695  0.104167  0.070529  0.264901  0.359223  0.081481  0.092784
2    0.508475  0.109375  0.050378  0.264901  0.407767  0.044444  0.226804
3    0.508475  0.109375  0.050378  0.264901  0.407767  0.044444  0.226804
4    0.220339  0.171875  0.050378  0.264901  0.475728  0.051852  0.061856
..        ...       ...       ...       ...       ...       ...       ...
995  0.864407  0.273438  0.114610  0.403974  0.728155  0.103704  0.103093
996  0.186441  0.065104  0.068010  0.754967  0.398058  0.140741  0.051546
997  0.169492  0.171875  0.094458  0.384106  0.398058  0.059259  0.103093
998  0.305085  0.138021  0.066751  0.384106  0.514563  0.125926  0.144330
999  0.576271  0.117188  0.076826  0.397351  0.368932  0.103704  0.092784

          LDL      VLDL       BMI
0    0.114583  0.011461  0.173913
1    0.187500  0.014327  0.139130
2    0.114583  0.011461  0.173913
3    0.114583  0.011461  0.173913
4    0.177083  0.008596  0.069565
..        ...       ...       ...
995  0.156250  0.014327  0.382609
996  0.218750  0.438395  0.633043
997  0.218750  0.229226  0.292174
998  0.270833  0.398281  0.747826
999  0.281250  0.017192  0.486957

[1000 rows x 10 columns]